2019-05-04T16:59:44.277+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-05-04T16:59:44.306+0000 I CONTROL  [initandlisten] MongoDB starting : pid=7 port=27017 dbpath=/data/db 64-bit host=0176576cc45d
2019-05-04T16:59:44.309+0000 I CONTROL  [initandlisten] db version v4.0.9
2019-05-04T16:59:44.313+0000 I CONTROL  [initandlisten] git version: fc525e2d9b0e4bceff5c2201457e564362909765
2019-05-04T16:59:44.314+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2019-05-04T16:59:44.314+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-05-04T16:59:44.315+0000 I CONTROL  [initandlisten] modules: enterprise 
2019-05-04T16:59:44.316+0000 I CONTROL  [initandlisten] build environment:
2019-05-04T16:59:44.316+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
2019-05-04T16:59:44.317+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-05-04T16:59:44.318+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-05-04T16:59:44.319+0000 I CONTROL  [initandlisten] options: {}
2019-05-04T16:59:44.340+0000 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2019-05-04T16:59:44.351+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1461M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2019-05-04T17:00:05.790+0000 I STORAGE  [initandlisten] WiredTiger message [1556989205:790195][7:0x7f46c1608a80], txn-recover: Main recovery loop: starting at 4/6400 to 5/256
2019-05-04T17:00:06.566+0000 I STORAGE  [initandlisten] WiredTiger message [1556989206:566464][7:0x7f46c1608a80], txn-recover: Recovering log 4 through 5
2019-05-04T17:00:07.218+0000 I STORAGE  [initandlisten] WiredTiger message [1556989207:218386][7:0x7f46c1608a80], txn-recover: Recovering log 5 through 5
2019-05-04T17:00:07.330+0000 I STORAGE  [initandlisten] WiredTiger message [1556989207:330040][7:0x7f46c1608a80], txn-recover: Set global recovery timestamp: 0
2019-05-04T17:00:07.409+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2019-05-04T17:00:07.511+0000 I CONTROL  [initandlisten] 
2019-05-04T17:00:07.511+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2019-05-04T17:00:07.512+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2019-05-04T17:00:07.513+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2019-05-04T17:00:07.513+0000 I CONTROL  [initandlisten] 
2019-05-04T17:00:07.514+0000 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2019-05-04T17:00:07.514+0000 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2019-05-04T17:00:07.515+0000 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2019-05-04T17:00:07.516+0000 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2019-05-04T17:00:07.517+0000 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2019-05-04T17:00:07.518+0000 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2019-05-04T17:00:07.519+0000 I CONTROL  [initandlisten] 
2019-05-04T17:00:07.695+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2019-05-04T17:00:07.706+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2019-05-04T17:00:14.712+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:44250 #1 (1 connection now open)
2019-05-04T17:00:14.717+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:44250 conn1: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.125-linuxkit" }, platform: "CPython 3.7.3.final.0" }
2019-05-04T17:00:15.185+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:44252 #2 (2 connections now open)
2019-05-04T17:00:15.188+0000 I NETWORK  [conn2] received client metadata from 127.0.0.1:44252 conn2: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.125-linuxkit" }, platform: "CPython 3.7.3.final.0" }
2019-05-04T17:00:16.726+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:44262 #3 (3 connections now open)
2019-05-04T17:00:16.731+0000 I NETWORK  [conn3] received client metadata from 127.0.0.1:44262 conn3: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.125-linuxkit" }, platform: "CPython 3.7.3.final.0" }
2019-05-04T17:03:11.624+0000 I NETWORK  [conn2] end connection 127.0.0.1:44252 (2 connections now open)
2019-05-04T17:03:11.625+0000 I NETWORK  [conn3] end connection 127.0.0.1:44262 (1 connection now open)
2019-05-04T17:03:12.673+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:44580 #4 (2 connections now open)
2019-05-04T17:03:12.675+0000 I NETWORK  [conn4] received client metadata from 127.0.0.1:44580 conn4: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.125-linuxkit" }, platform: "CPython 3.7.3.final.0" }
2019-05-04T17:03:21.459+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:44602 #5 (3 connections now open)
2019-05-04T17:03:21.463+0000 I NETWORK  [conn5] received client metadata from 127.0.0.1:44602 conn5: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.9.125-linuxkit" }, platform: "CPython 3.7.3.final.0" }
